### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by bliemli**
- Remove obsolete files
  - `helm-chart/values.yaml`
  - `workspace.yaml` < should be generated using `helm template` anyway to get up-to-date version
- Move build manifests to dedicated directory
  - Adapt build `context` in `docker/build-push-action@v3` actions
  - Remove `file` from `docker/build-push-action@v3` actions as `Dockerfile` is default anyway

### CODE REVIEW

**Review by splattner — CHANGES_REQUESTED** [review]
`helm-chart/values.yaml` is still needed for the webshell demo deployment. See https://github.com/acend/webshell-env/blob/main/.github/workflows/release.yaml#L98

**Comment by bliemli** [comment]
> `helm-chart/values.yaml` is still needed for the webshell demo deployment. See https://github.com/acend/webshell-env/blob/main/.github/workflows/release.yaml#L98

Do you see any issues setting the default `values.yaml` in `deploy/charts/webshell/` to the values used at the moment for the demo webshell? My fear is that a) people are not aware that changes in the `deploy/charts/webshell/values.yaml` would have to be mirrored in `helm-chart/values.yaml` and b) it's easier to manage just one values file.

**Comment by sybnex** [comment]
Does renovate react if the Dockerfile is not at root anymore? Does anybody knows that?

**Comment by bliemli** [comment]
> Does renovate react if the Dockerfile is not at root anymore? Does anybody knows that?

The `fileMatch` regex looks incorrect anyway, shouldn't it be `(^|\/|\.)Dockerfile$`? This way it wouldn't matter in which directory the Dockerfile is in.

**Review by sybnex — COMMENTED** [review]
It a kind of unusual for me, because we have the Dockerfile and build scripts in root. And the other stuff in a dir named "deliver" or at root as well.

But I don't care. LGTM

PS: I'm not aware of the "values.yaml" stuff which seba mentioned

**Comment by splattner** [comment]
> Do you see any issues setting the default `values.yaml` in `deploy/charts/webshell/` to the values used at the moment for the demo webshell? My fear is that a) people are not aware that changes in the `deploy/charts/webshell/values.yaml` would have to be mirrored in `helm-chart/values.yaml` and b) it's easier to manage just one values file.

hmm, I'd rather keep `deploy/charts/webshell/values.yaml` as general as possible without any environment specific values. This pattern is normally used (basically all available public helm charts)  in a Chart's values.yaml file and then overwrite those, when needed, to instantiate a chart into a release.
So `helm-chart/values.yaml` should not be just a mirror for `deploy/charts/webshell/values.yaml` but only changed environment specific values.
This is the intended usage of a helm chart and changes in the helm chart requires (us) to be aware and adapt those changes where the chart is used. To be better aware of changes in the helm chart, a changelog file or release notes might be an option.

We use the same pattern in all of our training repos. As an example the kubernetes-basics-training with [values.yaml](https://github.com/acend/kubernetes-basics-training/blob/main/helm-chart/values.yaml) and then the default [values.yaml](https://github.com/acend/helm-charts/blob/main/charts/acend-training-chart/values.yaml) from our acend-training-chart.

I agree, in this `webshell-env` repo, it might be confusing as it is a mix between the helm chart and the webshell-demo deployment. But in my opinion, changing the default chart value to address this issue, is not the right way.

**Comment by splattner** [comment]
btw, all the other changes are fine for me! :+1:

**Comment by bliemli** [comment]
> > Do you see any issues setting the default `values.yaml` in `deploy/charts/webshell/` to the values used at the moment for the demo webshell? My fear is that a) people are not aware that changes in the `deploy/charts/webshell/values.yaml` would have to be mirrored in `helm-chart/values.yaml` and b) it's easier to manage just one values file.
> 
> hmm, I'd rather keep `deploy/charts/webshell/values.yaml` as general as possible without any environment specific values. This pattern is normally used (basically all available public helm charts) in a Chart's values.yaml file and then overwrite those, when needed, to instantiate a chart into a release. So `helm-chart/values.yaml` should not be just a mirror for `deploy/charts/webshell/values.yaml` but only changed environment specific values. This is the intended usage of a helm chart and changes in the helm chart requires (us) to be aware and adapt those changes where the chart is used. To be better aware of changes in the helm chart, a changelog file or release notes might be an option.
> 
> We use the same pattern in all of our training repos. As an example the kubernetes-basics-training with [values.yaml](https://github.com/acend/kubernetes-basics-training/blob/main/helm-chart/values.yaml) and then the default [values.yaml](https://github.com/acend/helm-charts/blob/main/charts/acend-training-chart/values.yaml) from our acend-training-chart.
> 
> I agree, in this `webshell-env` repo, it might be confusing as it is a mix between the helm chart and the webshell-demo deployment. But in my opinion, changing the default chart value to address this issue, is not the right way.

I now simply moved the values file for the demo webshell to the chart's directory and renamed it to `values-demo.yaml`. I think this it is more obvious what the purpose of each of these values files is. What do you think?

**Comment by splattner** [comment]
i can live with that :+1:

**Pull request merged**
